import { Routes } from '@angular/router';
import { HomeComponent } from '../../home/home.component';
import { MapaFisicoComponent } from 'app/mapa-fisico/mapa-fisico.component';
import { MapaHidrografiaComponent } from 'app/mapa-hidrografia/mapa-hidrografia.component';
import { MapaOrografiaComponent } from 'app/mapa-Orografia/mapa-Orografia.component';
import { MapaPoliticoComponent } from 'app/mapa-Politico/mapa-Politico.component';
import { GeneralidadComponent } from 'app/generalidad/generalidad.component';
import { RegionComponent } from 'app/region/region.component';
import { AspectoFisicoComponent } from 'app/aspecto-Fisico/aspecto-Fisico.component';
import { TendenciasComponent } from 'app/tendencias/tendencias.component';
import { GeneralidadPoblacionComponent } from 'app/generalidad-poblacion/generalidad-poblacion.component';
import { BreveHistoriaComponent } from 'app/breve-historia/breve-historia.component';
import { DemografiaComponent } from 'app/demografia/demografia.component';
import { GobiernoComponent } from 'app/gobierno/gobierno.component';
import { EconomiaComponent } from 'app/economia/economia.component';
import { CulturaComponent } from 'app/cultura/cultura.component';
import { EscudoComponent } from 'app/escudo/escudo.component';
import { BanderaComponent } from 'app/bandera/bandera.component';
import { HimnoComponent } from 'app/himno/himno.component';
import { VideoComponent } from 'app/video/video.component';
import { PangeaComponent } from 'app/pangea/pangea.component';
import { SismoComponent } from 'app/sismo/sismo.component';
import { EfectoInvernaderoComponent } from 'app/efecto-invernadero/efecto-invernadero.component';
import { DestruccionCapaDeOzonoComponent } from 'app/destruccion-capa-de-ozono/destruccion-capa-de-ozono.component';
import { FenomenoNinoComponent } from 'app/fenomeno-nino/fenomeno-nino.component';
import { CiclonesTropicalesComponent } from 'app/ciclones-tropicales/ciclones-tropicales.component';
import { SaltoDelAngelComponent } from 'app/salto-del-angel/salto-del-angel.component';
import { CanalPanamaComponent } from 'app/canal-panama/canal-panama.component';
import { CoordenadasGeograficasComponent } from 'app/coordenadas-geograficas/coordenadas-geograficas.component';
import { MeridianosParalelosComponent } from 'app/meridianos-paralelos/meridianos-paralelos.component';
import { CorrientesMaritimasComponent } from 'app/corrientes-maritimas/corrientes-maritimas.component';
import { DesiertosComponent } from 'app/desiertos/desiertos.component';
import { VulcanismoComponent } from 'app/vulcanismo/vulcanismo.component';
import { IslasComponent } from 'app/islas/islas.component';
import { PlacasTectonicasComponent } from 'app/placas-tectonicas/placas-tectonicas.component';


export const AdminLayoutRoutes: Routes = [
    { path: 'dashboard',              component: HomeComponent },
    { path: 'mapaFisico',             component: MapaFisicoComponent },
    { path: 'mapaHidrografia',        component: MapaHidrografiaComponent },
    { path: 'mapaPolitico',           component: MapaPoliticoComponent },
    { path: 'mapaOrografia',          component: MapaOrografiaComponent },
    { path: 'generalidad',            component: GeneralidadComponent },
    { path: 'region',                 component: RegionComponent },
    { path: 'aspectoFisico',          component: AspectoFisicoComponent },
    { path: 'tendencias',             component: TendenciasComponent },
    { path: 'generalidadPoblacion',   component: GeneralidadPoblacionComponent },
    { path: 'breveHistoria',          component: BreveHistoriaComponent },
    { path: 'demografia',             component: DemografiaComponent },
    { path: 'gobierno',               component: GobiernoComponent },
    { path: 'economia',               component: EconomiaComponent },
    { path: 'cultura',                component: CulturaComponent },
    { path: 'escudo',                 component: EscudoComponent },
    { path: 'bandera',                component: BanderaComponent },
    { path: 'himno',                  component: HimnoComponent },
    { path: 'video',                  component: VideoComponent },
    { path: 'pangea',                 component: PangeaComponent },
    { path: 'sismo',                  component: SismoComponent },
    { path: 'efectoInvernadero',      component: EfectoInvernaderoComponent },
    { path: 'destruccionCapaDeOzono', component: DestruccionCapaDeOzonoComponent },
    { path: 'fenomenoNino',           component: FenomenoNinoComponent },
    { path: 'ciclonesTropicales',     component: CiclonesTropicalesComponent },
    { path: 'saltoDelAngel',          component: SaltoDelAngelComponent },
    { path: 'canalPanama',            component: CanalPanamaComponent },
    { path: 'coordenadasGeograficas', component: CoordenadasGeograficasComponent },
    { path: 'meridianosParalelos',    component: MeridianosParalelosComponent },
    { path: 'corientesMaritimas',     component: CorrientesMaritimasComponent },
    { path: 'desiertos',              component: DesiertosComponent },
    { path: 'vulcanismo',             component: VulcanismoComponent },
    { path: 'islas',                  component: IslasComponent },
    { path: 'placasTectonicas',       component: PlacasTectonicasComponent },

];
